export const defaultTeams = [
    // { name: '4', pilotOne: 'Gendel', pilotTwo: 'Filimonov', pilotThree: '', pilotFour: '' },
    // { name: '3', pilotOne: 'Tsovyan', pilotTwo: 'Aghamiryan', pilotThree: '', pilotFour: '' },
    // { name: '11', pilotOne: 'Aksyutin', pilotTwo: 'Kutdiusov', pilotThree: '', pilotFour: '' },
    // { name: '7', pilotOne: 'Kuzovov', pilotTwo: 'Shor', pilotThree: 'Travkin', pilotFour: 'Safonnikova' },
    // { name: '5', pilotOne: 'Grigoriani', pilotTwo: 'Golovachenko', pilotThree: '', pilotFour: '' },
    // { name: '13', pilotOne: 'Tsimakuridze', pilotTwo: 'Khidesheli', pilotThree: 'Kovziridze', pilotFour: '' },
    // { name: '1', pilotOne: 'Hovhannisyan', pilotTwo: 'Sargsyan', pilotThree: '', pilotFour: '' },
];

// export const defaultStintsByPilots = {
//     '4': [
//         { pilot: 'Golovachenko', kart: '4' },
//         { pilot: 'Yakunin', kart: '5' },
//         { pilot: 'Golovachenko', kart: '1' },
//         { pilot: 'Yakunin', kart: '7' },
//         { pilot: 'Golovachenko', kart: '1' },
//         { pilot: 'Yakunin', kart: '12' },

export const defaultStintsByPilots = {
    // '4': [
    //     { pilot: 'Filimonov', kart: '4' },
    //     { pilot: 'Gendel', kart: '1' },
    //     { pilot: 'Gendel', kart: '4' },
    //     { pilot: 'Filimonov', kart: '1' },
    //     { pilot: 'Filimonov', kart: '4' },
    //     { pilot: 'Gendel', kart: '14' },
    //     { pilot: 'Gendel', kart: '5' },
    //     { pilot: 'Filimonov', kart: '14' },
    // ],
    // '3': [
    //     { pilot: 'Tsovyan', kart: '3' },
    //     { pilot: 'Aghamiryan', kart: '4' },
    //     { pilot: 'Tsovyan', kart: '8' },
    //     { pilot: 'Aghamiryan', kart: '13' },
    //     { pilot: 'Tsovyan', kart: '3' },
    //     { pilot: 'Aghamiryan', kart: '14' },
    //     { pilot: 'Tsovyan', kart: '11' },
    //     { pilot: 'Aghamiryan', kart: '1' },
    // ],
    // '11': [
    //     { pilot: 'Aksyutin', kart: '11' },
    //     { pilot: 'Kutdiusov', kart: '14' },
    //     { pilot: 'Aksyutin', kart: '3' },
    //     { pilot: 'Kutdiusov', kart: '5' },
    //     { pilot: 'Aksyutin', kart: '11' },
    //     { pilot: 'Kutdiusov', kart: '8' },
    //     { pilot: 'Kutdiusov', kart: '4' },
    //     { pilot: 'Kutdiusov', kart: '7' },
    // ],
    // '7': [
    //     { pilot: 'Shor', kart: '7' },
    //     { pilot: 'Travkin', kart: '5' },
    //     { pilot: 'Safonnikova', kart: '11' },
    //     { pilot: 'Kuzovov', kart: '8' },
    //     { pilot: 'Shor', kart: '13' },
    //     { pilot: 'Shor', kart: '11' },
    //     { pilot: 'Kuzovov', kart: '7' },
    //     { pilot: 'Travkin', kart: '3' },
    // ],
    // '5': [
    //     { pilot: 'Golovachenko', kart: '5' },
    //     { pilot: 'Golovachenko', kart: '13' },
    //     { pilot: 'Grigoriani', kart: '7' },
    //     { pilot: 'Grigoriani', kart: '1' },
    //     { pilot: 'Grigoriani', kart: '14' },
    //     { pilot: 'Golovachenko', kart: '7' },
    //     { pilot: 'Golovachenko', kart: '1' },
    //     { pilot: 'Grigoriani', kart: '13' },
    // ],
    // '13': [
    //     { pilot: 'Kovziridze', kart: '13' },
    //     { pilot: 'Khidesheli', kart: '11' },
    //     { pilot: 'Tsimakuridze', kart: '13' },
    //     { pilot: 'Tsimakuridze', kart: '3' },
    //     { pilot: 'Kovziridze', kart: '5' },
    //     { pilot: 'Khidesheli', kart: '4' },
    //     { pilot: 'Kovziridze', kart: '3' },
    //     { pilot: 'Tsimakuridze', kart: '5' },
    // ],
    // '1': [
    //     { pilot: 'Hovhannisyan', kart: '1' },
    //     { pilot: 'Sargsyan', kart: '8' },
    //     { pilot: 'Hovhannisyan', kart: '14' },
    //     { pilot: 'Sargsyan', kart: '7' },
    //     { pilot: 'Hovhannisyan', kart: '1' },
    //     { pilot: 'Sargsyan', kart: '13' },
    //     { pilot: 'Hovhannisyan', kart: '8' },
    //     { pilot: 'Sargsyan', kart: '11' },
    // ],
};
